# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170803_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='to_address',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
