# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0039_collectionviewrestriction'),
        ('home', '0003_auto_20170804_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThankYouPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('thank_you_text', models.CharField(default='Thank you for Subscription', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
